services:
  - type: web
    name: kipi-games
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: "8080"
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1
